### ISSUE TITLE
Integrated dida365 login

### ISSUE THREAD

**Issue by laffitto** [hansdoebel/n8n-nodes-ticktick#2]
Hello, I am a user from China and I really like the plugin you made. But TickTick has an independent app in China called dida365. Here is the API document for [dida365](https://developer.dida365.com/docs#/openapi). It looks like same with [TickTick](https://developer.ticktick.com/docs#/openapi). I would like to know if it is possible to add an option to log in using the dida365 service in the credentials.

**Comment by hansdoebel** [comment]
Thanks for your kind words about the plugin - I am glad to hear that you find it useful! I appreciate your suggestion to integrate Dida365. I've never heard of it, is it really popular in China? At first I thought it was a clone, but it seems to be legit?

I've taken a look at the API documentation for Dida365, and it does indeed have some similarities to the TickTick API. 

Before proceeding with the implementation, I would like to delve deeper into the specifics of the Dida365 API, particularly around authentication processes and any potential differences from the TickTick API. 

At first glance, I think I would rather code another node than implement the credentials because of the different API URL endpoints. I will definitely look into this more next week if I can successfully register and try it out.

**Comment by laffitto** [comment]
Yes, ticktick is actually a product from Chinese team. In China, it is called [dida356](https://dida365.com), and ticktick is launched for overseas users. Chinese users will choose dida365. They are essentially the same product, with only some minor functional differences due to different user groups. I hope you can register dida365 and test it. It's logic is exactly the same as ticktick.

**Comment by hansdoebel** [comment]
I released the package! It works locally, but I haven't tested it on my server yet. Let me know if there are any problems and I will try to help. ✌🏽 [n8n-nodes-dida](https://www.npmjs.com/package/n8n-nodes-dida)

**Comment by laffitto** [comment]
It works well. Thank you for your contribution！
